### ISSUE TITLE
I want maintenance.

### ISSUE THREAD

**Issue by PTOM76** [CrazyB0y/PipePump#16]
Can you please invite me to this repository and CurseForge?
Modrinth, if possible, please.

CurseForge: https://www.curseforge.com/members/pitan76/projects
Modrinth: https://modrinth.com/user/pitan76

**Comment by CrazyB0y** [comment]
Hi! Sorry for the long response time, life is difficult some times. I add u to repo and to curseforge

**Comment by PTOM76** [comment]
Thanks!
